### PR TITLE
fix (dashboard): configuring "Disable New Users" modifies the wrong setting

### LINKED ISSUE #2912: dashboard: configuring "Disable New Users" modifies the wrong setting
Under settings -> authentication we have the setting "Disable new Users" which seems to disable sign ups rather than the `disableNewUsers` setting. We should fix this and add disable sign ups now that we are in the process as I think we don't have it.

### PR DESCRIPTION
**Pull request by dbm03**
Resolves #2912

### CODE REVIEW

File: dashboard/src/features/orgs/projects/authentication/settings/components/DisableSignUpsSettings/DisableSignUpsSettings.tsx [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+export type DisableSignUpsFormValues = Yup.InferType<typeof validationSchema>;
+
+export default function DisableSignUpsSettings() {
+  const { openDialog } = useDialog();
+  const isPlatform = useIsPlatform();
+  const { maintenanceActive } = useUI();
+  const localMimirClient = useLocalMimirClient();
+  const { project } = useProject();
+  const [updateConfig] = useUpdateConfigMutation({
+    refetchQueries: [GetAuthenticationSettingsDocument],
```
Comment (onehassan) [inline dashboard/src/features/orgs/projects/authentication/settings/components/DisableSignUpsSettings/DisableSignUpsSettings.tsx:34]:
```suggestion
```

can we remove this as this will trigger a reload - we should rely on either res

**Review by onehassan — COMMENTED** [review]
left a comment

File: dashboard/src/features/orgs/projects/authentication/settings/components/DisableSignUpsSettings/DisableSignUpsSettings.tsx (hunk 1 above)
Comment (dbm03) [reply dashboard/src/features/orgs/projects/authentication/settings/components/DisableSignUpsSettings/DisableSignUpsSettings.tsx:34]: On it

**Comment by dbarrosop** [comment]
There is something wrong in this PR, the setting doesn't seem to work. I have the following config in a test project:

```toml
[auth.signUp]
disableNewUsers = false
enabled = true
```

and the dashboard shows:

Screenshot 2024-11-06 at 09 23 25

**Review by dbarrosop — APPROVED** [review]

**Review by onehassan — APPROVED** [review]
