### PR TITLE
fix(dashboard): remove custom domains from settings

### LINKED ISSUE #3566: bug: no way to remove custom domains using the dashboard

### PR DESCRIPTION
**Pull request by dbm03**
### **User description**
Resolves #3566

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Enable removal of custom domains by allowing empty values

- Refactor submit button disable logic using `useMemo` hook

- Remove `maintenanceActive` dependency from form validation

- Add dynamic success messages for domain updates and removals

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["User Input"] --> B["Form Validation"]
  B --> C{"Empty Domain?"}
  C -- "Yes" --> D["Remove Domain"]
  C -- "No" --> E["Verify Domain"]
  E --> F["Update Domain"]
  D --> G["Success Message"]
  F --> G
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>AuthDomain.tsx</strong><dd><code>Enable auth domain removal with improved validation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/custom-domains/settings/components/AuthDomain/AuthDomain.tsx

<ul><li>Refactored submit button disable logic with <code>useMemo</code> to allow empty <br>domain submission<br> <li> Changed <code>ingresses</code> to nullable type, setting to <code>null</code> when domain is <br>empty<br> <li> Added dynamic success messages for update vs removal operations<br> <li> Replaced <code>register</code> with controlled input using <code>setValue</code> and <code>onChange</code></ul>

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3782/files#diff-4b8e1e15fc7df8fe284298d5ab47dbc3f554888f98e39f84c4ac995f35c10c86">+39/-25</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>HasuraDomain.tsx</strong><dd><code>Enable Hasura domain removal with validation updates</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/custom-domains/settings/components/HasuraDomain/HasuraDomain.tsx

<ul><li>Implemented <code>useMemo</code> for submit button disable logic allowing empty <br>values<br> <li> Modified <code>ingresses</code> to accept <code>null</code> for domain removal<br> <li> Added conditional success messages based on operation type<br> <li> Converted input to controlled component with manual state management</ul>

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3782/files#diff-334177cc61035493cfca775de96635b58d98a28856067048dcfba6cd7f255978">+42/-26</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>ServerlessFunctionsDomain.tsx</strong><dd><code>Enable serverless functions domain removal with logic refactor</code></dd></summary>
<hr>

dashboard/src/features/orgs/projects/custom-domains/settings/components/ServerlessFunctionsDomain/ServerlessFunctionsDomain.tsx

<ul><li>Refactored button disable logic using <code>useMemo</code> to support empty domain <br>values<br> <li> Changed <code>ingresses</code> type to nullable for removal functionality<br> <li> Added dynamic success messages for update and removal scenarios<br> <li> Replaced form registration with controlled input pattern</ul>

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3782/files#diff-e7cf7b49535f816a9c2c60cf1f8b975036bd6a988e4295529e999075d72044ef">+41/-26</a>&nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>VerifyDomain.tsx</strong><dd><code>Add conditional save instruction and state reset</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/custom-domains/settings/components/VerifyDomain/VerifyDomain.tsx

<ul><li>Added <code>saveEnabled</code> prop to conditionally display save instruction<br> <li> Implemented <code>useEffect</code> to reset verification state on hostname/value <br>changes<br> <li> Updated verification success message to respect <code>saveEnabled</code> flag</ul>

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3782/files#diff-ffb92b1b31befe065c50f7fe7fd2f099cdda624b4956655a80d5d0004a132e19">+10/-2</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

</details>

___

### CODE REVIEW

File: dashboard/src/features/orgs/projects/custom-domains/settings/components/AuthDomain/AuthDomain.tsx [hunk 1]
```diff
@@ -61,6 +59,23 @@ export default function AuthDomain() {
   const { networking } = data?.config?.auth?.resources || {};
   const initialValue = networking?.ingresses?.[0]?.fqdn?.[0];
 
+  const { formState, watch, setValue } = form;
+  const isDirty = Object.keys(formState.dirtyFields).length > 0;
+
+  const auth_fqdn = watch('auth_fqdn');
+
+  const submitButtonDisabled = useMemo(() => {
```
Comment (robertkasza) [inline dashboard/src/features/orgs/projects/custom-domains/settings/components/AuthDomain/AuthDomain.tsx]: Isn't useMemo an overkill here? I mea useMemeo will check every render that the dependencies have changed or not we might as well just calculate the value because there is no "heavy"(might not be the best word here) operation to calculate the if the button should be disabled or not.

What do you think?

File: dashboard/src/features/orgs/projects/custom-domains/settings/components/HasuraDomain/HasuraDomain.tsx [hunk 2]
```diff
@@ -66,6 +64,23 @@ export default function HasuraDomain() {
     }
   }, [data, loading, form, initialValue]);
 
+  const { formState, watch, setValue } = form;
+  const isDirty = Object.keys(formState.dirtyFields).length > 0;
+
+  const hasura_fqdn = watch('hasura_fqdn');
+
+  const submitButtonDisabled = useMemo(() => {
```
Comment (robertkasza) [inline dashboard/src/features/orgs/projects/custom-domains/settings/components/HasuraDomain/HasuraDomain.tsx]: Same question here.

File: dashboard/src/features/orgs/projects/custom-domains/settings/components/ServerlessFunctionsDomain/ServerlessFunctionsDomain.tsx [hunk 3]
```diff
@@ -68,6 +66,23 @@ export default function ServerlessFunctionsDomain() {
     }
   }, [data, loading, form, initialValue]);
 
+  const { formState, watch, setValue } = form;
+  const isDirty = Object.keys(formState.dirtyFields).length > 0;
+
+  const functions_fqdn = watch('functions_fqdn');
+
+  const submitButtonDisabled = useMemo(() => {
```
Comment (robertkasza) [inline dashboard/src/features/orgs/projects/custom-domains/settings/components/ServerlessFunctionsDomain/ServerlessFunctionsDomain.tsx]: same here.

File: dashboard/src/features/orgs/projects/custom-domains/settings/components/AuthDomain/AuthDomain.tsx (hunk 1 above)
Comment (dbm03) [reply dashboard/src/features/orgs/projects/custom-domains/settings/components/AuthDomain/AuthDomain.tsx]: Should I add a function like `const isSubmitButtonDisabled = () => {return true/false}`

that computes the output? 

I used `useMemo` because I thought computing it with a function makes it more readable with the `if` and `return` statements (but obviously I could just add a function that computes the value without having to use `useMemo`).

Comment (dbm03) [reply dashboard/src/features/orgs/projects/custom-domains/settings/components/AuthDomain/AuthDomain.tsx]: I added this in the last commit instead, what do you think?

```tsx
const submitButtonDisabled = (() => {
    // compute logic...
})();
```

**Review by robertkasza — APPROVED** [review]
