### PR TITLE
fix (dashboard): run services with secrets in the command field

### LINKED ISSUE #3070: dashboard: run services with secrets in the command breaks the form
If you try to configure the command:

```
mycmd --myflag={{ secrets.MYSECRET }}
```

the dashboard parses it incorrectly returning the array:

```
[ "mycmd", "--myflag={{", "secrets.MYSECRET", "}}" ]
```

I think this is unfortunate but expected. The most accurate and reliable solution would be to change the form to a list of inputs:

```
[ "mycmd" ]
[ "--myflag={{ secrets.MYSECRET }}" ]
```

that way we avoid parsing issues.

### PR DESCRIPTION
**Pull request by dbm03**
### **User description**
Fixes #3070

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Refactor command input to list format

- Fix parsing issues with secrets in commands

- Improve UI for command input section

- Update related components and types

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>ServiceForm.tsx</strong><dd><code>Replace command input with new CommandFormSection component</code></dd></summary>
<hr>

dashboard/src/features/orgs/projects/services/components/ServiceForm/ServiceForm.tsx

<li>Remove shell-quote parsing<br> <li> Replace single command input with CommandFormSection<br> <li> Update service configuration to use new command format

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3208/files#diff-a02746694d45a84390d09b49a1b3eec85c25a8bd9a70b4834ee5af1ba82cb88e">+3/-24</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>ServiceFormTypes.ts</strong><dd><code>Update command validation schema and type definition</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/services/components/ServiceForm/ServiceFormTypes.ts

<li>Update command validation schema<br> <li> Change command type from string to array of objects

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3208/files#diff-e9e0545b8c213ce04a08f9b04aedc81f96a031429e2ac9ac9e19d47982c112dc">+5/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>CommandFormSection.tsx</strong><dd><code>Create new CommandFormSection component for improved command input</code></dd></summary>
<hr>

dashboard/src/features/orgs/projects/services/components/ServiceForm/components/CommandFormSection/CommandFormSection.tsx

<li>Add new CommandFormSection component<br> <li> Implement dynamic command input fields<br> <li> Add space detection warning<br> <li> Include tooltip with usage instructions

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3208/files#diff-952b9cf5789c2075527c9289b6464a1a678bb3e2f1073e5493eb871eec33c650">+112/-0</a>&nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Add index file for CommandFormSection component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/services/components/ServiceForm/components/CommandFormSection/index.ts

- Export CommandFormSection component

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3208/files#diff-e39d0bfb2f4a8ea0386eb5852324a1aeb2a7da161ffed09929653703a8ec525e">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>ServiceConfirmationDialog.tsx</strong><dd><code>Update import path in ServiceConfirmationDialog</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/services/components/ServiceForm/components/ServiceConfirmationDialog/ServiceConfirmationDialog.tsx

- Update import path for ServiceFormValues type

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3208/files#diff-0f7e83b481fe5f81e80d03aa47ec2c7b812322519a9dda4cbe9dfab0d2c37d03">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>ServicesList.tsx</strong><dd><code>Adjust command formatting in ServicesList component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/services/components/ServicesList/ServicesList.tsx

- Update command formatting in initialData

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3208/files#diff-643c818a248c42950336289392ac97ed9ef5c670ff8e47b80588b9802844d28a">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>run.tsx</strong><dd><code>Modify command formatting in run page configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/pages/orgs/[orgSlug]/projects/[appSubdomain]/run.tsx

- Update command formatting in parsedConfig

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3208/files#diff-b113fc9ab0c229c90cdcb792b15404544813072a2d2ad9fb140746628b83db8c">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>famous-seahorses-taste.md</strong><dd><code>Add changeset for command field secrets fix</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.changeset/famous-seahorses-taste.md

<li>Add changeset for minor version bump<br> <li> Describe fix for secrets in command field

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3208/files#diff-c71b086d2f313eeb58415afe90205c8e3161c83587b659e9d5ae594bff48b96a">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about PR-Agent usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

**Comment by dbarrosop** [comment]
I am concerned this change will lead to issues with people not understanding what needs to happen here. I'd suggest a few changes:

1. Add a clarification note in the (i);

```
Specify the command and its arguments to run the service. Note that the command and/or its parameters need to be specified on different lines. For instance:
- node
- server.js
- --port=3000
```

2. If you detect a space in a particular row show a warning. Maybe make the rectangle yellow and show a warning `A space was detected, make sure it is intended, check the tooltip for details`.

File: dashboard/src/features/orgs/projects/services/components/ServiceForm/ServiceForm.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ import { removeTypename } from '@/utils/helpers';
 import { yupResolver } from '@hookform/resolvers/yup';
 import { useEffect, useMemo, useState } from 'react';
 import { FormProvider, useForm } from 'react-hook-form';
-import { parse } from 'shell-quote';
```
Comment (robertkasza) [inline dashboard/src/features/orgs/projects/services/components/ServiceForm/ServiceForm.tsx:43]: Can we mark the "shell-quote" package for deletion? The only place this is used is in the old workplace file. Once we remove them we need to remove this package too.

File: dashboard/src/features/orgs/projects/services/components/ServiceForm/components/CommandFormSection/CommandFormSection.tsx [hunk 2]
```diff
@@ -0,0 +1,123 @@
+import { Alert } from '@/components/ui/v2/Alert';
```
Comment (robertkasza) [inline dashboard/src/features/orgs/projects/services/components/ServiceForm/components/CommandFormSection/CommandFormSection.tsx:1]: I do not like that we are using the ui/v2. I am guessing this component is surrounded with UI/v2 components. If we are continue on this way we are always going to have two version of the UI.

It's okay for now, but we need to have a discussion about when to use which version.

**Review by robertkasza — APPROVED** [review]

File: dashboard/src/features/orgs/projects/services/components/ServiceForm/ServiceForm.tsx (hunk 1 above)
Comment (dbm03) [reply dashboard/src/features/orgs/projects/services/components/ServiceForm/ServiceForm.tsx:43]: Will add this to the remove legacy workspaces PR. Thx
