### PR TITLE
fix (dashboard): split postgres version if using a beta like 17.2-0.0.0-beta1

### LINKED ISSUE #3175: dashboard: split in the dashboard for postgres version is b0rk3d if using something like 17.2-0.0.0-beta1

### PR DESCRIPTION
**Pull request by dbm03**
### **User description**
Fixes #3175

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Fix Postgres version splitting for beta versions

- Improve major version validation in settings

- Add utility function for version splitting

- Implement tests for version splitting function

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>DatabaseServiceVersionSettings.tsx</strong><dd><code>Update version handling in DatabaseServiceVersionSettings</code></dd></summary>
<hr>

dashboard/src/features/orgs/projects/database/settings/components/DatabaseServiceVersionSettings/DatabaseServiceVersionSettings.tsx

<li>Import new <code>splitPostgresMajorMinorVersions</code> utility<br> <li> Update major version validation to check for positive number<br> <li> Use new utility function to split Postgres versions

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3211/files#diff-a982b817513fc173371f7468ad642f99ee0c914e5990a48992fc1fa5e230765f">+9/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Add export for new version splitting utility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/database/settings/utils/splitPostgresMajorMinorVersions/index.ts

- Export `splitPostgresMajorMinorVersions` function

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3211/files#diff-d1fd3a4c358d12a8141c71fa1b73ecfbb422c5ddab3b77212e4b45cbbb759a25">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>splitPostgresMajorMinorVersions.ts</strong><dd><code>Implement Postgres version splitting utility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/database/settings/utils/splitPostgresMajorMinorVersions/splitPostgresMajorMinorVersions.ts

<li>Implement <code>splitPostgresMajorMinorVersions</code> function<br> <li> Split version string into major and minor parts

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3211/files#diff-2c41895bcbcaa13eb34bfb8321640dcdc2757dd920e40e46f2dcd0670c3e56a2">+11/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>splitPostgresMajorMinorVersions.test.ts</strong><dd><code>Add tests for Postgres version splitting utility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

dashboard/src/features/orgs/projects/database/settings/utils/splitPostgresMajorMinorVersions/splitPostgresMajorMinorVersions.test.ts

<li>Add tests for <code>splitPostgresMajorMinorVersions</code> function<br> <li> Test regular and beta Postgres versions

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3211/files#diff-d6320a0f90b9fc7d0d1e4bea1434daa2ece4b326a442256a2b727219dc958efb">+15/-0</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>twenty-pets-brake.md</strong><dd><code>Add changeset for version bump and fix description</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

.changeset/twenty-pets-brake.md

<li>Add changeset for minor version bump<br> <li> Describe fix for Postgres beta version splitting

</details>

  </td>
  <td><a href="https://github.com/nhost/nhost/pull/3211/files#diff-da03f8241486698793641c7a3ec58e11cdbb185b5920bd6bd7b281cd8513f5c3">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about PR-Agent usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

File: dashboard/src/features/orgs/projects/database/settings/utils/splitPostgresMajorMinorVersions/splitPostgresMajorMinorVersions.ts [hunk 1]
```diff
@@ -0,0 +1,11 @@
+export default function splitPostgresMajorMinorVersions(version: string) {
```
Comment (dbarrosop) [inline dashboard/src/features/orgs/projects/database/settings/utils/splitPostgresMajorMinorVersions/splitPostgresMajorMinorVersions.ts:1]: it shouldn't happen but I'd suggest testing that a postgres version includes no dots. In which case we should treat the thing as the major. I.e., `version: 15`. Again, it shouldn't happen but better safe than sorry.

Comment (dbm03) [reply dashboard/src/features/orgs/projects/database/settings/utils/splitPostgresMajorMinorVersions/splitPostgresMajorMinorVersions.ts:7]: I've just added this check in the last commit. Thx

**Comment by dbarrosop** [comment]
Mmm, I just tested the version `version = "14.1.2.3.3.4.5"` and in the dashboard I only see 14 as major and 1 as minor.

File: dashboard/src/features/orgs/projects/database/settings/components/DatabaseServiceVersionSettings/DatabaseServiceVersionSettings.tsx [hunk 2]
```diff
@@ -142,10 +149,12 @@ export default function DatabaseServiceVersionSettings() {
         majorToMinorVersions[major] = [];
       }
 
-      majorToMinorVersions[major].push({
-        label: minor,
-        value: minor,
-      });
+      if (minor !== '') {
```
Comment (robertkasza) [inline dashboard/src/features/orgs/projects/database/settings/components/DatabaseServiceVersionSettings/DatabaseServiceVersionSettings.tsx:152]: nit: You could use isNotEmptyValue utility function.

**Review by dbarrosop — APPROVED** [review]

**Review by robertkasza — APPROVED** [review]
